//! Default configuration, mirroring `DefaultConfig()` in `config.go`.

use std::time::Duration;

use crate::types::*;

/// Port of `DefaultConfig`.
pub fn default_config() -> Config {
    Config {
        sites: vec![],
        rules: vec![],
        ml: MlConfig {
            enabled: false,
            endpoint: "http://127.0.0.1:9090".to_string(),
            timeout_sec: 5,
            max_retries: 2,
            fallback_mode: "allow".to_string(),
            min_score: 0.5,
            model_name: String::new(),
        },
        redis: RedisConfig {
            enabled: false,
            addr: "127.0.0.1:6379".to_string(),
            password: String::new(),
            db: 0,
            pool_size: 10,
            ttl: 3600,
        },
        db: DbConfig {
            driver: "sqlite3".to_string(),
            dsn: "fortresswaf.db".to_string(),
            max_open: 25,
            max_idle: 5,
        },
        logging: LoggingConfig {
            level: "info".to_string(),
            format: "text".to_string(),
            output: "stdout".to_string(),
            verbose: false,
        },
        tls: TlsConfig {
            enabled: false,
            cert_file: String::new(),
            key_file: String::new(),
            min_version: "1.2".to_string(),
            http2_enabled: true,
            ocsp_enabled: false,
            acme_enabled: false,
            acme_email: String::new(),
            acme_domains: vec![],
            acme_cache_dir: String::new(),
        },
        admin: AdminConfig {
            port: 8443,
            enabled: true,
            mtls: false,
            ca_cert: String::new(),
            cert_file: String::new(),
            key_file: String::new(),
            api_keys: vec![],
            cors_origins: vec![],
            trusted_proxies: vec![],
        },
        jwt: JwtConfig {
            enabled: false,
            jwks_url: String::new(),
            issuers: vec![],
            audiences: vec![],
            algorithms: vec!["RS256".to_string(), "ES256".to_string()],
            secret: String::new(),
        },
        oauth: OAuthConfig {
            enabled: false,
            ..Default::default()
        },
        graphql: GraphQlConfig {
            enabled: false,
            max_depth: 10,
            max_cost: 1000,
            max_aliases: 15,
            max_batch_size: 1,
            max_tokens: 10000,
            block_introspection: false,
            block_schema: false,
            strict_validation: true,
            allowed_operations: vec!["query".to_string(), "mutation".to_string()],
            restricted_fields: vec![],
        },
        mtls: MtlsConfig {
            enabled: false,
            ca_file: String::new(),
            client_auth: "no-client-certs".to_string(),
            skip_verify: false,
            policy_oid: String::new(),
            verify_depth: 5,
            fail_on_error: false,
            early_auth: false,
            username_header: "X-Client-Cert-User".to_string(),
        },
        websocket: WebSocketConfig {
            enabled: false,
            max_frame_size: 65536,
            max_message_size: 0,
            max_depth: 10,
            max_frames_per_min: 0,
            max_bytes_per_min: 0,
            block_on_limit: false,
            allowed_types: vec![],
            strict_mode: true,
            enable_ping: true,
            enable_pong: true,
            enable_close: true,
            connection_timeout: Duration::ZERO,
        },
        siem: SiemConfig {
            enabled: false,
            export_interval: Duration::from_secs(10),
            batch_size: 100,
            exporters: vec![],
        },
        rewrite_rules: vec![],
        sqli: FeatureConfig { enabled: false },
        xss: FeatureConfig { enabled: false },
        rce: FeatureConfig { enabled: false },
        ddos: DDoSConfig {
            enabled: false,
            per_ip_rate: 0,
            per_endpoint_rate: 0,
            global_rate: 0,
            ban_seconds: 0,
        },
        protocol: FeatureConfig { enabled: false },
        bot: BotConfig::default(),
        api_protect: FeatureConfig { enabled: false },
        upload: FeatureConfig { enabled: false },
        credential: CredentialConfig {
            enabled: false,
            max_attempts: 5,
            window_sec: 300,
            block_duration_sec: 3600,
            login_paths: vec![],
        },
        geo: GeoConfig::default(),
        rate_limit: RateLimitConfig::default(),
        session: SessionConfig::default(),
        reputation: FeatureConfig::default(),
        rules_cfg: FeatureConfig::default(),
        captcha: CaptchaConfig {
            enabled: false,
            provider: String::new(),
            site_key: String::new(),
            secret: String::new(),
            score: 0.5,
        },
        response_inspect: ResponseInspectConfig {
            enabled: false,
            inspect_body: true,
            block: false,
            sensitive_patterns: vec![],
        },
        soap: SoapConfig {
            enabled: false,
            strict_schema: false,
            max_depth: 10,
        },
        grpc: GrpcConfig {
            enabled: false,
            max_msg_size: 4194304,
            rate_limit: 100,
        },
        prometheus: PrometheusConfig {
            enabled: false,
            path: "/metrics".to_string(),
            port: 9090,
        },
        ja3: FeatureConfig { enabled: true },
        behavioral: BehavioralConfig {
            enabled: false,
            reputation: true,
            velocity: true,
            path_entropy: true,
            threshold: 50.0,
            window_sec: 60,
            max_requests: 100,
        },
        wasm: WasmConfig {
            enabled: false,
            module_dir: "wasm_modules".to_string(),
            max_memory_pages: 10,
            modules: vec![],
        },
        desync: DesyncConfig {
            enabled: false,
            max_body_size: 10485760,
            strict_cl: true,
            detect_obs_fold: true,
        },
        adaptive: AdaptiveConfig {
            enabled: false,
            js_script_path: "challenge.js".to_string(),
            tarpit_delay_ms: 30000,
            captcha_score: 0.5,
            challenge_ttl: 300,
        },
        ebpf: EbpfConfig {
            enabled: false,
            interface: "eth0".to_string(),
            port: 80,
            sample_rate: 10,
        },
        parser_hardening: FeatureConfig { enabled: true },
        shadow_mode: FeatureConfig { enabled: false },
        learning_mode: FeatureConfig { enabled: false },
        performance: PerformanceConfig {
            enabled: false,
            max_regex_ms: 1000,
            max_wasm_ms: 5000,
            max_memory_mb: 512,
            max_concurrency: 0,
            circuit_threshold: 5,
        },
        server: ServerConfig::default(),
        training: TrainingConfig::default(),
        file_path: String::new(),
    }
}
